steps:
- name: gcr.io/jr-dev-host-proj-001/pulumi-node
  entrypoint: /bin/sh
  args:
  - '-c'
  - 'yarn install && pulumi login gs://jimit-pulumi-demo-state && pulumi stack select stage && pulumi up -y'
  env: ["PULUMI_CONFIG_PASSPHRASE=$_PASSPHRASE"]