steps:
- name: gcr.io/jr-dev-host-proj-001/pulumi-python
  entrypoint: /bin/sh
  args:
  - '-c'
  - 'pip install -r requirements.txt && pulumi org set-default rangrasjimit && pulumi login && pulumi stack select rangrasjimit/cicd-demo/dev && pulumi up -y'
  env: 
  - 'PULUMI_ACCESS_TOKEN=$_TOKEN'
  - 'PULUMI_CONFIG_PASSPHRASE=$_PASSPHRASE'